name: Build Core
description: Install dependencies and build core
runs:
  using: composite
  steps:
    - name: Build Core
      shell: bash
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
      run: pnpm --filter core run build