name: Test suites for client and contracts

on: [push]

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-72bc4f4e616c6e2b79ee3582301fbb1d38660857

      - name: Build client bundle
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm --filter client run build

      - name: Run tests in client
        run: pnpm --filter client run test

      - name: Build contracts
        run: pnpm --filter contracts run build

      - name: Create .env with anvil private key
        run: echo "PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" > packages/contracts/.env

      - name: Run tests in contracts
        run: pnpm --filter contracts run test
